package entities;
// Generated 06/11/2018 18:48:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contagem generated by hbm2java
 */
public class Contagem  implements java.io.Serializable {


     private Integer idContagem;
     private String nomeProjeto;
     private int tipoContagem;
     private int totalPontos;
     private Set funcoeses = new HashSet(0);

    public Contagem() {
    }

	
    public Contagem(String nomeProjeto, int tipoContagem, int totalPontos) {
        this.nomeProjeto = nomeProjeto;
        this.tipoContagem = tipoContagem;
        this.totalPontos = totalPontos;
    }
    public Contagem(String nomeProjeto, int tipoContagem, int totalPontos, Set funcoeses) {
       this.nomeProjeto = nomeProjeto;
       this.tipoContagem = tipoContagem;
       this.totalPontos = totalPontos;
       this.funcoeses = funcoeses;
    }
   
    public Integer getIdContagem() {
        return this.idContagem;
    }
    
    public void setIdContagem(Integer idContagem) {
        this.idContagem = idContagem;
    }
    public String getNomeProjeto() {
        return this.nomeProjeto;
    }
    
    public void setNomeProjeto(String nomeProjeto) {
        this.nomeProjeto = nomeProjeto;
    }
    public int getTipoContagem() {
        return this.tipoContagem;
    }
    
    public void setTipoContagem(int tipoContagem) {
        this.tipoContagem = tipoContagem;
    }
    public int getTotalPontos() {
        return this.totalPontos;
    }
    
    public void setTotalPontos(int totalPontos) {
        this.totalPontos = totalPontos;
    }
    public Set getFuncoeses() {
        return this.funcoeses;
    }
    
    public void setFuncoeses(Set funcoeses) {
        this.funcoeses = funcoeses;
    }




}


